# --- Frontend Dockerfile for Angular ---
FROM node:22-alpine as build
WORKDIR /app

# Use only package.json for install to avoid lockfile version conflicts
COPY package.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist/backoffice-tre/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
